export enum ArtType {
  'NONE' = 'NONE',
  'WATERCOLOR' = 'WATERCOLOR',
  'PENCIL_DRAWING' = 'PENCIL_DRAWING',
  'ACRYLIC_PAINTING' = 'ACRYLIC_PAINTING',
  'OIL_PAINTING' = 'OIL_PAINTING',
}

export enum ImageStatus {
  NONE = 'NONE',
  CHANGED = 'CHANGED',
  UPLOADED = 'UPLOADED',
}
