import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Faustina } from 'next/font/google';
import { ReactNode } from 'react';

import { ThemeProvider } from '@/components/theme-provider';

const faustina = Faustina({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${faustina.className} flex flex-col min-h-dvh`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
